# site settings
title:  Selected Works
subtitle: by RealToughCandy
email: realtoughcandy@gmail.com
description: I'm a Web Developer & Designer. 
#baseurl: "/Portfolio" # the subpath of your site, e.g. /blog
url: "https://realtoughcandy.github.io/" # the base hostname & protocol for your site
author: RTC
street_address: 12 Spacedust Lane
city: Jupiteria
state: Mars
zip_code: 90210
country: Milky Way Galaxy
phone: (555) Hire-Candy

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 8

# social settings
500px_url:
facebook_url:
github_url: https://github.com/RealToughCandy
pinterest_url:
slack_url: https://www.RealToughCandy.slack.com
youtube_url: https://www.youtube.com/RealToughCandy
twitter_url: https://twitter.com/RealToughCandy

# build settings
markdown: kramdown

sass:
  style: compressed
